apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy15
  labels:
    app: autodeploy15
  namespace: namespace-workflow-1700583284114
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy15
  template:
    metadata:
      labels:
        app: autodeploy15
    spec:
      containers:
        - name: autodeploy15
          image: acrworkflow1700583284114.azurecr.io/image-workflow-1700583284114:latest
          ports:
            - containerPort: 5000