apiVersion: v1
kind: Service
metadata:
  name: autodeploy15
  namespace: namespace-workflow-1700583284114
spec:
  type: LoadBalancer
  selector:
    app: autodeploy15
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000